# Generated by Django 6.1.1 on 2026-09-18 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('status', models.CharField(choices=[('held', 'Held in escrow'), ('released', 'Released to worker'), ('refunded', 'Refunded to employer'), ('disputed', 'Disputed')], default='held', max_length=10)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='jobs.booking')),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
    ]
