# Generated by Django 6.1.1 on 2026-09-18 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_radius_km', models.PositiveSmallIntegerField(default=10)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='worker_docs/id_proof/')),
                ('is_live', models.BooleanField(default=False, help_text='Profile is publicly visible')),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='core.skillcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='worker_portfolio/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quality_grade', models.CharField(choices=[('ungraded', 'Ungraded'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='ungraded', max_length=10)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged as mismatched/suspicious')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.skillcategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='workers.worker')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['city', 'skill_category'], name='workers_wor_city_07d35c_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['-trust_score'], name='workers_wor_trust_s_68b9f5_idx'),
        ),
    ]
