# Generated by Django 6.1.1 on 2026-09-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('review', 'Review'), ('worker_profile', 'Worker profile')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('cancellation_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('punctuality_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('model_version', models.CharField(default='v1', max_length=30)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_logs', to='workers.worker')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_demand', models.PositiveIntegerField(help_text='Predicted number of job postings')),
                ('confidence_lower', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence_upper', models.PositiveIntegerField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.skillcategory')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['city', 'skill_category'], name='ml_models_d_city_afe4b2_idx')],
            },
        ),
    ]
